// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEQPFpoY0ItuWoxNSZMk8YbGFWb6rnkx0',
    appId: '1:837672523367:web:a298fc9c6f85031bb1a6c2',
    messagingSenderId: '837672523367',
    projectId: 'project-uas-279c1',
    authDomain: 'project-uas-279c1.firebaseapp.com',
    storageBucket: 'project-uas-279c1.appspot.com',
    measurementId: 'G-2601EQLG8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB68gfitXlCARCkRzY0Q5ZdXtvQaY1lh4k',
    appId: '1:837672523367:android:8b21bd908800af44b1a6c2',
    messagingSenderId: '837672523367',
    projectId: 'project-uas-279c1',
    storageBucket: 'project-uas-279c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuDaVUPKaBPdB6Z-kDCEaTt2o1v9xGAu0',
    appId: '1:837672523367:ios:41ceb3a2735a6ceeb1a6c2',
    messagingSenderId: '837672523367',
    projectId: 'project-uas-279c1',
    storageBucket: 'project-uas-279c1.appspot.com',
    iosBundleId: 'com.example.redwallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuDaVUPKaBPdB6Z-kDCEaTt2o1v9xGAu0',
    appId: '1:837672523367:ios:67cbcde264a60fe3b1a6c2',
    messagingSenderId: '837672523367',
    projectId: 'project-uas-279c1',
    storageBucket: 'project-uas-279c1.appspot.com',
    iosBundleId: 'com.example.redwallet.RunnerTests',
  );
}
